package net.aggregat4.javatags.tags;

import net.aggregat4.javatags.attributes.AttributeType;
import net.aggregat4.javatags.attributes.Attributes;

import static net.aggregat4.javatags.attributes.Attributes.*;
import static net.aggregat4.javatags.tags.TagType.Constants.CLOSING_TAG;
import static net.aggregat4.javatags.tags.TagType.Constants.CONTENT_ALLOWED;

public enum TagType {
//    a("a", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck, Attributes.href, Attributes.target, Attributes.download, Attributes.rel, Attributes.hreflang, Attributes.type}, CLOSING_TAG),
//    abbr("abbr", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck, Attributes.title}, CLOSING_TAG),
//    address("address", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck}, CLOSING_TAG),
//    area("area", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck, Attributes.alt, Attributes.coords, Attributes.download, Attributes.href, Attributes.hreflang, Attributes.rel, Attributes.shape, Attributes.target, Attributes.type}, CLOSING_TAG),
//    article("article", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck}, CLOSING_TAG),
//    aside("aside", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck}, CLOSING_TAG),
//    audio("audio", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck, Attributes.src, Attributes.crossorigin, Attributes.preload, Attributes.autoplay, Attributes.mediagroup, Attributes.loop, Attributes.muted, Attributes.controls}, CLOSING_TAG),
//    base("base", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck, Attributes.href, Attributes.target}, CLOSING_TAG),
//    bdi("bdi", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck, Attributes.dir}, CLOSING_TAG),
//    bdo("bdo", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck, Attributes.dir}, CLOSING_TAG),
//    blockquote("blockquote", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck, Attributes.cite}, CLOSING_TAG),
//    body("body", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck, Attributes.onafterprint, Attributes.onbeforeprint, Attributes.onbeforeunload, Attributes.onhashchange, Attributes.onmessage, Attributes.onoffline, Attributes.ononline, Attributes.onpagehide, Attributes.onpageshow, Attributes.onpopstate, Attributes.onstorage, Attributes.onunload}, CLOSING_TAG),
//    br("br", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck}, CLOSING_TAG),
//    button("button", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck, Attributes.autofocus, Attributes.disabled, Attributes.form, Attributes.formaction, Attributes.formenctype, Attributes.formmethod, Attributes.formnovalidate, Attributes.formtarget, Attributes.name, Attributes.type, Attributes.value}, CLOSING_TAG),
//    canvas("canvas", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck, Attributes.width, Attributes.height}, CLOSING_TAG),
//    caption("caption", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck}, CLOSING_TAG),
//    col("col", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck, Attributes.span}, CLOSING_TAG),
//    colgroup("colgroup", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck, Attributes.span}, CLOSING_TAG),
//    data("data", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck, Attributes.value}, CLOSING_TAG),
//    datalist("datalist", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck}, CLOSING_TAG),
//    dd("dd", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck}, CLOSING_TAG),
//    del("del", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck, Attributes.cite, Attributes.datetime}, CLOSING_TAG),
//    dfn("dfn", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck, Attributes.title}, CLOSING_TAG),
//    div("div", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck}, CLOSING_TAG),
//    dl("dl", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck}, CLOSING_TAG),
//    dt("dt", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck}, CLOSING_TAG),
//    em("em", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck}, CLOSING_TAG),
//    embed("embed", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck, Attributes.src, Attributes.type, Attributes.width, Attributes.height}, CLOSING_TAG),
//    fieldset("fieldset", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck, Attributes.disabled, Attributes.form, Attributes.name}, CLOSING_TAG),
//    figcaption("figcaption", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck}, CLOSING_TAG),
//    figure("figure", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck}, CLOSING_TAG),
//    footer("footer", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck}, CLOSING_TAG),
//    form("form", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck, Attributes.accept-charset, Attributes.action, Attributes.autocomplete, Attributes.enctype, Attributes.method, Attributes.name, Attributes.novalidate, Attributes.target}, CLOSING_TAG),
//    h1("h1", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck}, CLOSING_TAG),
//    head("head", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck}, CLOSING_TAG),
//    header("header", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck}, CLOSING_TAG),
//    hr("hr", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck}, CLOSING_TAG),
//    html("html", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck, Attributes.manifest}, CLOSING_TAG),
//    iframe("iframe", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck, Attributes.src, Attributes.srcdoc, Attributes.name, Attributes.sandbox, Attributes.width, Attributes.height}, CLOSING_TAG),
//    img("img", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck, Attributes.alt, Attributes.src, Attributes.crossorigin, Attributes.usemap, Attributes.ismap, Attributes.width, Attributes.height}, CLOSING_TAG),
//    input("input", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck, Attributes.accept, Attributes.alt, Attributes.autocomplete, Attributes.autofocus, Attributes.checked, Attributes.dirname, Attributes.disabled, Attributes.form, Attributes.formaction, Attributes.formenctype, Attributes.formmethod, Attributes.formnovalidate, Attributes.formtarget, Attributes.height, Attributes.list, Attributes.max, Attributes.maxlength, Attributes.min, Attributes.minlength, Attributes.multiple, Attributes.name, Attributes.pattern, Attributes.placeholder, Attributes.readonly, Attributes.required, Attributes.size, Attributes.src, Attributes.step, Attributes.type, Attributes.value, Attributes.width, Attributes.pattern}, CLOSING_TAG),
//    ins("ins", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck, Attributes.cite, Attributes.datetime}, CLOSING_TAG),
//    keygen("keygen", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck, Attributes.autofocus, Attributes.challenge, Attributes.disabled, Attributes.form, Attributes.keytype, Attributes.name}, CLOSING_TAG),
//    label("label", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck, Attributes.form, Attributes.forAttr}, CLOSING_TAG),
//    legend("legend", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck}, CLOSING_TAG),
//    li("li", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck, Attributes.ol}, CLOSING_TAG),
//    link("link", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck, Attributes.href, Attributes.crossorigin, Attributes.rel, Attributes.media, Attributes.hreflang, Attributes.type, Attributes.sizes, Attributes.title}, CLOSING_TAG),
//    main("main", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck}, CLOSING_TAG),
//    map("map", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck, Attributes.name}, CLOSING_TAG),
//    meta("meta", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck, Attributes.name, Attributes.http-equiv, Attributes.content, Attributes.charset}, CLOSING_TAG),
//    meter("meter", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck, Attributes.value, Attributes.min, Attributes.max, Attributes.low, Attributes.high, Attributes.optimum}, CLOSING_TAG),
//    nav("nav", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck}, CLOSING_TAG),
//    noscript("noscript", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck}, CLOSING_TAG),
//    object("object", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck, Attributes.data, Attributes.type, Attributes.typemustmatch, Attributes.name, Attributes.usemap, Attributes.form, Attributes.width, Attributes.height}, CLOSING_TAG),
//    ol("ol", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck, Attributes.reversed, Attributes.start, Attributes.type}, CLOSING_TAG),
//    optgroup("optgroup", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck, Attributes.disabled, Attributes.label}, CLOSING_TAG),
//    option("option", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck, Attributes.disabled, Attributes.label, Attributes.selected, Attributes.value}, CLOSING_TAG),
//    output("output", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck, Attributes.forAttr, Attributes.form, Attributes.name}, CLOSING_TAG),
//    p("p", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck}, CLOSING_TAG),
//    param("param", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck, Attributes.name, Attributes.value}, CLOSING_TAG),
//    pre("pre", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck}, CLOSING_TAG),
//    progress("progress", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck, Attributes.value, Attributes.max}, CLOSING_TAG),
//    q("q", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck, Attributes.cite}, CLOSING_TAG),
//    rb("rb", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck}, CLOSING_TAG),
//    rp("rp", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck}, CLOSING_TAG),
//    rt("rt", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck}, CLOSING_TAG),
//    rtc("rtc", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck}, CLOSING_TAG),
//    ruby("ruby", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck}, CLOSING_TAG),
//    s("s", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck}, CLOSING_TAG),
//    script("script", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck, Attributes.src, Attributes.type, Attributes.charset, Attributes.async, Attributes.defer, Attributes.crossorigin}, CLOSING_TAG),
//    section("section", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck}, CLOSING_TAG),
//    select("select", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck, Attributes.autofocus, Attributes.disabled, Attributes.form, Attributes.multiple, Attributes.name, Attributes.required, Attributes.size}, CLOSING_TAG),
//    source("source", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck, Attributes.src, Attributes.type}, CLOSING_TAG),
//    span("span", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck}, CLOSING_TAG),
//    style("style", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck, Attributes.media, Attributes.type, Attributes.title}, CLOSING_TAG),
//    sub("sub", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck}, CLOSING_TAG),
//    table("table", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck, Attributes.border}, CLOSING_TAG),
//    tbody("tbody", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck}, CLOSING_TAG),
//    td("td", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck, Attributes.colspan, Attributes.rowspan, Attributes.headers}, CLOSING_TAG),
//    template("template", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck}, CLOSING_TAG),
//    textarea("textarea", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck, Attributes.autocomplete, Attributes.autofocus, Attributes.cols, Attributes.dirname, Attributes.disabled, Attributes.form, Attributes.maxlength, Attributes.minlength, Attributes.name, Attributes.placeholder, Attributes.readonly, Attributes.required, Attributes.rows, Attributes.wrap}, CLOSING_TAG),
//    tfoot("tfoot", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck}, CLOSING_TAG),
//    th("th", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck, Attributes.colspan, Attributes.rowspan, Attributes.headers, Attributes.scope, Attributes.abbr}, CLOSING_TAG),
//    thead("thead", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck}, CLOSING_TAG),
//    time("time", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck, Attributes.datetime}, CLOSING_TAG),
//    title("title", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck}, CLOSING_TAG),
//    tr("tr", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck}, CLOSING_TAG),
//    track("track", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck, Attributes.kind, Attributes.src, Attributes.srclang, Attributes.label, Attributes.defaultAttr}, CLOSING_TAG),
//    ul("ul", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck}, CLOSING_TAG),
//    video("video", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck, Attributes.src, Attributes.crossorigin, Attributes.poster, Attributes.preload, Attributes.autoplay, Attributes.mediagroup, Attributes.loop, Attributes.muted, Attributes.controls, Attributes.width, Attributes.height}, CLOSING_TAG),
//    wbr("wbr", CONTENT_ALLOWED, new AttributeType[] {Attributes.id, Attributes.classAttr, Attributes.style, Attributes.titleAttr, Attributes.lang, Attributes.translate, Attributes.dir, Attributes.hidden, Attributes.tabIndex, Attributes.accessKey, Attributes.accessKeyLabel, Attributes.contentEditable, Attributes.isContentEditable, Attributes.spellcheck}, CLOSING_TAG),
    ;

    private String name;
    private boolean contentAllowed;
    private AttributeType[] allowedAttributeTypes;
    private boolean closingTag;

    TagType(String name, boolean contentAllowed, AttributeType[] allowedAttributeTypes, boolean closingTag) {
        this.name = name;
        this.contentAllowed = contentAllowed;
        this.allowedAttributeTypes = allowedAttributeTypes;
        this.closingTag = closingTag;
    }

    public String getName() {
        return name;
    }

    public boolean isContentAllowed() {
        return contentAllowed;
    }

    public AttributeType[] getAllowedAttributeTypes() {
        return allowedAttributeTypes;
    }

    public boolean isClosingTag() {
        return closingTag;
    }

    static class Constants {
        public static final AttributeType[] NO_ATTRIBUTES_ALLOWED = new AttributeType[0];

        // http://www.w3.org/TR/html5/dom.html#global-attributes and http://www.w3.org/TR/html5/dom.html#htmlelement
//        public static final AttributeType[] STANDARD_HTML_ATTRIBUTES = new AttributeType[] {
//            id, classAttr, style, titleAttr, lang, translate, dir,
//            hidden, tabIndex, accessKey, accessKeyLabel, contentEditable,
//            isContentEditable, spellcheck};
        public static final AttributeType[] STANDARD_HTML_ATTRIBUTES = new AttributeType[]{
            id,
            classAttr,
            style,
            titleAttr,
            lang,
            translate,
            dir,
            hidden,
            tabIndex,
            accessKey,
            accessKeyLabel,
            contentEditable,
            isContentEditable,
            spellcheck };
        // Aliases for readability
        public static final boolean CONTENT_ALLOWED = true;
        public static final boolean NO_CONTENT_ALLOWED = false;
        public static final boolean CLOSING_TAG = true;
        public static final boolean NON_CLOSING_TAG = false;
    }

}
